/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:980148ac-21e5-46ca-9fdd-699aa49a33f0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sIpZ7bOME",
    "aws_user_pools_web_client_id": "190lb7po03gcqc74fon8v63vbn",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://b31q6ect9k.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
